version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TuContraseñaSegura123
    ports:
      - "1433:1433"
    networks:
      - sql_network
    restart: always
    volumes:
      - sql_data:/var/opt/mssql

networks:
  sql_network:
    driver: bridge

volumes:
  sql_data:
    driver: local